version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: ./src/.env  # Path to your .env file
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/my_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: yarn start

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
